import { useEffect, useRef, useState } from "react";
import DatePicker from "react-datepicker";
import { useNavigate } from "react-router-dom";

import "react-datepicker/dist/react-datepicker.css";

import Button from "@/components/Button";
import ButtonBack from "@/components/ButtonBack";
import Message from "@/components/Message";
import Spinner from "@/components/Spinner";

import { useCities } from "@/hooks/useCities";
import { useUrlPosition } from "@/hooks/useUrlPosition";

import { convertToEmoji } from "@/utils/convertToEmoji";

import styles from "./Form.module.css";

import type { City } from "@/types";

const REVERSE_GEOCODE_URL = import.meta.env.VITE_API_REVERSE_GEOCODE_URL;

function Form() {
  const emojiRef = useRef<string | null>(null);
  const emoji = emojiRef.current;

  const [cityName, setCityName] = useState("");
  const [country, setCountry] = useState("");
  const [date, setDate] = useState(new Date());
  const [isLoadingGeocoding, setisLoadingGeocoding] = useState(false);
  const [notes, setNotes] = useState("");
  const [geocodingError, setGeocodingError] = useState<string | null>(null);

  const { addCity, error: contextError, isLoading } = useCities();

  const navigate = useNavigate();

  const [lat, lng] = useUrlPosition();

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!cityName || !emoji || !date || !(lat && lng)) return;

    const newCity = {
      cityName,
      country,
      emoji,
      date: String(date),
      notes,
      position: {
        lat: +lat,
        lng: +lng,
      },
      // id will be generated by the API
    };

    await addCity(newCity as City);
    navigate("/app/cities");
  }

  useEffect(() => {
    if (lat && lng) {
      const queryString = `latitude=${lat}&longitude=${lng}`;

      setisLoadingGeocoding(true);
      setGeocodingError(null);
      fetch(`${REVERSE_GEOCODE_URL}?${queryString}`)
        .then((response) => response.json())
        .then(
          (data: {
            city?: string;
            countryCode: string;
            countryName?: string;
            locality: string;
          }) => {
            if (!data.countryName) {
              emojiRef.current = null;
              setCityName("");
              setCountry("");
              throw new Error(
                "That doesn't seem to be a city. Try somewhere else 😯"
              );
            } else {
              const emoji = convertToEmoji(data.countryCode);
              emojiRef.current = emoji;
              setCityName(data.city || data.locality);
              setCountry(data.countryName);
            }
          }
        )
        .catch((error: Error) => setGeocodingError(error.message))
        .finally(() => setisLoadingGeocoding(false));
    }
  }, [lat, lng]);

  if (isLoadingGeocoding) return <Spinner />;

  if (!lat || !lng)
    return <Message message="Start by clicking on the map 🗺️" />;

  if (geocodingError) return <Message message={geocodingError} />;
  if (contextError) return <Message message={contextError} />;

  return (
    <form
      // eslint-disable-next-line @typescript-eslint/no-misused-promises
      onSubmit={handleSubmit}
      className={`${styles.form} ${isLoading ? styles.loading : ""}`}
    >
      <div className={styles.row}>
        <label htmlFor="cityName">City name</label>
        <input
          id="cityName"
          onChange={(event) => setCityName(event.target.value)}
          value={cityName}
        />
        <span className={styles.flag}>{emoji}</span>
      </div>

      <div className={styles.row}>
        <label htmlFor="date">When did you go to {cityName}?</label>
        <DatePicker
          id="date"
          selected={date}
          onChange={(date: Date) => setDate(date)}
          dateFormat="yyyy-MM-dd"
        />
      </div>

      <div className={styles.row}>
        <label htmlFor="notes">Notes about your trip to {cityName}</label>
        <textarea
          id="notes"
          onChange={(event) => setNotes(event.target.value)}
          value={notes}
        />
      </div>

      <div className={styles.buttons}>
        <Button onClick={() => null}>Add</Button>
        <ButtonBack />
      </div>
    </form>
  );
}

export default Form;
